export const AGENT_LIMITS = {
  MAX_INTERESTS: 10,
  MAX_NAME_LENGTH: 20,
  MAX_CATCHPHRASE_LENGTH: 50,
} as const;

export const EVENT_LIMITS = {
  MIN_ROUNDS: 1,
  MAX_ROUNDS: 5,
  DEFAULT_ROUNDS: 2,
  MIN_TURNS_PER_AGENT: 2,
  MAX_TURNS_PER_AGENT: 10,
  DEFAULT_TURNS_PER_AGENT: 5,
} as const;

export const PAGINATION = {
  DEFAULT_PAGE_SIZE: 50,
  MAX_PAGE_SIZE: 100,
} as const;

export const POLLING = {
  EVENT_POLL_INTERVAL_MS: 3000,
  WATCH_POLL_INTERVAL_MS: 5000,
  WATCH_POLL_JITTER_MS: 2000,
} as const;
